language: python
sudo: required
dist: xenial

arch:
  - amd64
  - ppc64le

services:
  - docker

before_install:
- docker pull rroemhild/test-openldap
- docker run -d --privileged -p 127.0.0.1:389:389 -p 127.0.0.1:636:636 rroemhild/test-openldap

python:
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install pipenv
  - pipenv install --dev

script: py.test
